# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAINWIDOWS.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.color2qian = QtWidgets.QPushButton(self.centralwidget)
        self.color2qian.setGeometry(QtCore.QRect(260, 290, 31, 31))
        self.color2qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color2qian.setText("")
        self.color2qian.setObjectName("color2qian")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(560, 280, 31, 121))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -40, 911, 461))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/image/bcakground2.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.inputpath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputpath.setGeometry(QtCore.QRect(160, 40, 371, 51))
        self.inputpath.setStyleSheet("border: 2px solid black; /* 设置边框为黑色，可以根据需要调整宽度 */\n"
"border-radius: 15px; /* 设置边框圆角，可以根据需要调整 */")
        self.inputpath.setObjectName("inputpath")
        self.color6hou = QtWidgets.QPushButton(self.centralwidget)
        self.color6hou.setGeometry(QtCore.QRect(360, 350, 31, 31))
        self.color6hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color6hou.setText("")
        self.color6hou.setObjectName("color6hou")
        self.color7hou = QtWidgets.QPushButton(self.centralwidget)
        self.color7hou.setGeometry(QtCore.QRect(530, 350, 31, 31))
        self.color7hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color7hou.setText("")
        self.color7hou.setObjectName("color7hou")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 350, 51, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.color2hou = QtWidgets.QPushButton(self.centralwidget)
        self.color2hou.setGeometry(QtCore.QRect(360, 290, 31, 31))
        self.color2hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color2hou.setText("")
        self.color2hou.setObjectName("color2hou")
        self.color8qian = QtWidgets.QPushButton(self.centralwidget)
        self.color8qian.setGeometry(QtCore.QRect(590, 350, 31, 31))
        self.color8qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color8qian.setText("")
        self.color8qian.setObjectName("color8qian")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 280, 791, 121))
        self.label_4.setStyleSheet("background-color: rgba(255, 85, 127, 100);\n"
"border: 1px solid black; ")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(90, 330, 641, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.color1qian = QtWidgets.QPushButton(self.centralwidget)
        self.color1qian.setGeometry(QtCore.QRect(100, 290, 31, 31))
        self.color1qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color1qian.setText("")
        self.color1qian.setObjectName("color1qian")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(470, 350, 51, 31))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 290, 51, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(720, 280, 21, 121))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 290, 51, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(470, 290, 51, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.color3hou = QtWidgets.QPushButton(self.centralwidget)
        self.color3hou.setGeometry(QtCore.QRect(530, 290, 31, 31))
        self.color3hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color3hou.setText("")
        self.color3hou.setObjectName("color3hou")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(300, 350, 51, 31))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.color3qian = QtWidgets.QPushButton(self.centralwidget)
        self.color3qian.setGeometry(QtCore.QRect(430, 290, 31, 31))
        self.color3qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color3qian.setText("")
        self.color3qian.setObjectName("color3qian")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 280, 61, 121))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/image/heisequseban.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.color4qian = QtWidgets.QPushButton(self.centralwidget)
        self.color4qian.setGeometry(QtCore.QRect(590, 290, 31, 31))
        self.color4qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color4qian.setText("")
        self.color4qian.setObjectName("color4qian")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(742, 300, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"background-color: #ff66a3; /* 粉色 */ \n"
"/* 白色文字，可根据需要调整 */\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;\n"
"padding: 5px 5px;\n"
"font-size: 25px;\n"
"font-weight: bold;\n"
"border: 2px solid black; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(150, 0, 127, 100); /* 鼠标悬停时的颜色 */}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 30, 221, 231))
        self.label.setStyleSheet("border: 2px solid black; ")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/too.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.outputpath = QtWidgets.QLineEdit(self.centralwidget)
        self.outputpath.setGeometry(QtCore.QRect(160, 120, 371, 51))
        self.outputpath.setStyleSheet("border: 2px solid black; /* 设置边框为黑色，可以根据需要调整宽度 */\n"
"border-radius: 15px; /* 设置边框圆角，可以根据需要调整 */")
        self.outputpath.setObjectName("outputpath")
        self.color4hou = QtWidgets.QPushButton(self.centralwidget)
        self.color4hou.setGeometry(QtCore.QRect(690, 290, 31, 31))
        self.color4hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color4hou.setText("")
        self.color4hou.setObjectName("color4hou")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(228, 280, 31, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.output = QtWidgets.QPushButton(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(40, 120, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setStyleSheet("QPushButton{\n"
"background-color: #ff66a3; /* 粉色 */ \n"
"/* 白色文字，可根据需要调整 */\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;\n"
"padding: 5px 5px;\n"
"font-size: 25px;\n"
"font-weight: bold;\n"
"border: 2px solid black; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(150, 0, 127, 100); /* 鼠标悬停时的颜色 */}")
        self.output.setObjectName("output")
        self.color1hou = QtWidgets.QPushButton(self.centralwidget)
        self.color1hou.setGeometry(QtCore.QRect(200, 290, 31, 31))
        self.color1hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color1hou.setText("")
        self.color1hou.setObjectName("color1hou")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 30, 51, 231))
        self.label_3.setStyleSheet("border: 2px solid black; ")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/image/NAME.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 290, 51, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(390, 280, 31, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 350, 51, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/image/jiantou2.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.ModifyRGB = QtWidgets.QPushButton(self.centralwidget)
        self.ModifyRGB.setGeometry(QtCore.QRect(40, 200, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ModifyRGB.setFont(font)
        self.ModifyRGB.setStyleSheet("QPushButton{\n"
"background-color: #ff66a3; /* 粉色 */ \n"
"/* 白色文字，可根据需要调整 */\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;\n"
"padding: 5px 5px;\n"
"font-size: 25px;\n"
"font-weight: bold;\n"
"border: 2px solid black; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(150, 0, 127, 100); /* 鼠标悬停时的颜色 */}")
        self.ModifyRGB.setObjectName("ModifyRGB")
        self.color8hou = QtWidgets.QPushButton(self.centralwidget)
        self.color8hou.setGeometry(QtCore.QRect(690, 350, 31, 31))
        self.color8hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color8hou.setText("")
        self.color8hou.setObjectName("color8hou")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(80, 280, 16, 121))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.color5hou = QtWidgets.QPushButton(self.centralwidget)
        self.color5hou.setGeometry(QtCore.QRect(200, 350, 31, 31))
        self.color5hou.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color5hou.setText("")
        self.color5hou.setObjectName("color5hou")
        self.input = QtWidgets.QPushButton(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(40, 40, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.input.setFont(font)
        self.input.setStyleSheet("QPushButton{\n"
"background-color: #ff66a3; /* 粉色 */ \n"
"/* 白色文字，可根据需要调整 */\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 20px;\n"
"padding: 5px 5px;\n"
"font-size: 25px;\n"
"font-weight: bold;\n"
"border: 2px solid black; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(150, 0, 127, 100); /* 鼠标悬停时的颜色 */}")
        self.input.setObjectName("input")
        self.color7qian = QtWidgets.QPushButton(self.centralwidget)
        self.color7qian.setGeometry(QtCore.QRect(430, 350, 31, 31))
        self.color7qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color7qian.setText("")
        self.color7qian.setObjectName("color7qian")
        self.color5qian = QtWidgets.QPushButton(self.centralwidget)
        self.color5qian.setGeometry(QtCore.QRect(100, 350, 31, 31))
        self.color5qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color5qian.setText("")
        self.color5qian.setObjectName("color5qian")
        self.color6qian = QtWidgets.QPushButton(self.centralwidget)
        self.color6qian.setGeometry(QtCore.QRect(260, 350, 31, 31))
        self.color6qian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color6qian.setText("")
        self.color6qian.setObjectName("color6qian")
        self.background.raise_()
        self.label_4.raise_()
        self.color2qian.raise_()
        self.line_4.raise_()
        self.inputpath.raise_()
        self.color6hou.raise_()
        self.color7hou.raise_()
        self.label_10.raise_()
        self.color2hou.raise_()
        self.color8qian.raise_()
        self.line_6.raise_()
        self.color1qian.raise_()
        self.label_12.raise_()
        self.label_6.raise_()
        self.line_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.color3hou.raise_()
        self.label_13.raise_()
        self.color3qian.raise_()
        self.label_5.raise_()
        self.color4qian.raise_()
        self.pushButton_18.raise_()
        self.label.raise_()
        self.outputpath.raise_()
        self.color4hou.raise_()
        self.line_2.raise_()
        self.output.raise_()
        self.color1hou.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.line_3.raise_()
        self.label_11.raise_()
        self.ModifyRGB.raise_()
        self.color8hou.raise_()
        self.line.raise_()
        self.color5hou.raise_()
        self.input.raise_()
        self.color7qian.raise_()
        self.color5qian.raise_()
        self.color6qian.raise_()
        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.input.clicked.connect(MainWindow.ChooseInputDir)
        self.output.clicked.connect(MainWindow.ChooseOutDir)
        # 第一组
        self.color1qian.clicked.connect(lambda: MainWindow.GetColor(self.color1qian))
        self.color1hou.clicked.connect(lambda: MainWindow.GetColor(self.color1hou))
        # 第二组
        self.color2qian.clicked.connect(lambda: MainWindow.GetColor(self.color2qian))
        self.color2hou.clicked.connect(lambda: MainWindow.GetColor(self.color2hou))
        # 第三组
        self.color3qian.clicked.connect(lambda: MainWindow.GetColor(self.color3qian))
        self.color3hou.clicked.connect(lambda: MainWindow.GetColor(self.color3hou))
        # 第四组
        self.color4qian.clicked.connect(lambda: MainWindow.GetColor(self.color4qian))
        self.color4hou.clicked.connect(lambda: MainWindow.GetColor(self.color4hou))
        # 第五组
        self.color5qian.clicked.connect(lambda: MainWindow.GetColor(self.color5qian))
        self.color5hou.clicked.connect(lambda: MainWindow.GetColor(self.color5hou))
        # 第六组
        self.color6qian.clicked.connect(lambda: MainWindow.GetColor(self.color6qian))
        self.color6hou.clicked.connect(lambda: MainWindow.GetColor(self.color6hou))
        # 第七组
        self.color7qian.clicked.connect(lambda: MainWindow.GetColor(self.color7qian))
        self.color7hou.clicked.connect(lambda: MainWindow.GetColor(self.color7hou))
        # 第八组
        self.color8qian.clicked.connect(lambda: MainWindow.GetColor(self.color8qian))
        self.color8hou.clicked.connect(lambda: MainWindow.GetColor(self.color8hou))
        self.pushButton_18.clicked.connect(MainWindow.ResetRGBs)
        self.ModifyRGB.clicked.connect(MainWindow.Run)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "一键批量修改图片RGB颜色软件V1.0"))
        self.pushButton_18.setText(_translate("MainWindow", "重置"))
        self.output.setText(_translate("MainWindow", "OUTPUT"))
        self.ModifyRGB.setText(_translate("MainWindow", "一键批量修改RGB值"))
        self.input.setText(_translate("MainWindow", "INPUT"))
import resource_rc
